import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "./logo";
import NavBar from "./navbar";
import TextoSection from "./main";
import { Hero } from "./main";
import Button from "./button";
import Hero2 from "./site";
import { ImagemSection } from "./site";
import { Card1 } from "../../Card1";
import Serviços from "./services";
import { Article } from "./services";
import { Paragrafo } from "./faqsection";
import App from "./faqsection";
import { Questions } from "./faqsection";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Microcredito",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html>
    <body className="bg-pur-900 ">
      <header>
        <nav className="mt-5 bg-rose-700">
          <div className="">
            <div className="flex justify-center justify-around items-center">
               {/* Logo */}
                <Logo />
               {/* Menu NavBar */}
                <NavBar />
            </div>
          </div>
        </nav>
        <main className="container flex justify-center pt-4">
      <div className="flex flex-col">
        <TextoSection />
        <div className="flex flex-row ml-5">
          <Button />
        </div>
      </div>
      <Hero />
    </main>
      </header>
        {/* Section 1 */}
      <section className="bg-white">
        <div className="flex justify-center justify-around">
          <Hero2/>
          <ImagemSection/>
        </div>
    </section>

    {/* Section 2 */}
    <section>
          <h2 className="pt-7 m-5 text-2xl md:text-3xl lg:text-3xl font-bold mb-4 text-center">Lorem ipsum</h2>
                <p className="pt-9 m-5 text-1xl md:text-1xl lg:text-1xl mb-4 text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          <div className="pt-9 flex justify-center gap-5">
            {/* CARD'S */}
             <Card1 
              image="./img/snail-icon.png"
              title="Visão"
            />
             <Card1 
              image="./img/Old-Technology.png"
              title="Missão"
            />
             <Card1 
              image="./img/price-icon.png"
              title="Valores"
            />
          </div>
          </section>
                    {/* SECTION 2 */}
                    <div className="pt-9">
                <Serviços
              /></div>
              {/*  LAST SECTION */}

              <section className="pt-10">
                <Article/>
              </section>
              <section className="bg-white text-black pt-12">
                <App/>
                <Questions/>
              </section>
              <footer className="bg-rose-950">
                <Footer/>
              </footer>
    </body>
    </html>
  );
}
